backend:
  name: github
  repo: CCLEEMon/CCL
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "页面"
    files:
      - label: "首页"
        name: "index"
        file: "src/pages/index.astro"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }